# Unbind the default Ctrl+b
unbind C-b

# Set the prefix to Ctrl+a
set -g prefix C-a

# Ensure Ctrl+a can still be sent to other apps (by pressing it twice)
bind C-a send-prefix



#after ytvideo 
#Terminal and Display Settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on


#Splits
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"


# Press Prefix + r to reload the config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"


#Window Management
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


#history-limit
set -g history-limit 10000



#some tweaks to the status line 
set -g status-right "%H:%M"
set -g window-status-current-style "underscore"


#if running inside tmux, then change the stutus line to red
%if #{TMUX}
set -g status-bg red
%endif
